#!/bin/bash

# make sure we're in the root directory
if [ ! -f package.json ]; then
  echo "Please run this script from the root directory of the project"
  exit 1
fi

# Initialize and empty index.ts in the src directory
echo "// autogenerated" > ./src/index.ts

# Find all directories and subdirectories under src excluding ones that start with "_"
find ./src -type d ! -name "_*" | while read -r dir; do
  exportAdded=false

  # Prepare index.ts in the current directory
  [ -f "$dir/index.ts" ] && rm "$dir/index.ts"

  # Handle .ts files
  for file in "$dir"/*.ts; do
    if [ -e "$file" ] && [ "$(basename -- "$file")" != "index.ts" ]; then
      # Create index.ts if not yet created
      [ -f "$dir/index.ts" ] || echo "// autogenerated" > "$dir/index.ts"
      echo "export * from './$(basename -- "${file%.ts}")';" >> "$dir/index.ts"
      exportAdded=true
    fi
  done

  # Handle .d.ts files, but only if there isn't a corresponding .ts
  for file in "$dir"/*.d.ts; do
    if [ -e "$file" ]; then
      fileWithoutExt="${file%.d.ts}"
      if [ ! -f "$fileWithoutExt.ts" ]; then
        # Create index.ts if not yet created
        [ -f "$dir/index.ts" ] || echo "// autogenerated" > "$dir/index.ts"
        echo "export * from './$(basename -- "$fileWithoutExt")';" >> "$dir/index.ts"
        exportAdded=true
      fi
    fi
  done

  # Handle subdirectories
  for subdir in "$dir"/*; do
    if [ -d "$subdir" ] && [ -f "$subdir/index.ts" ]; then
      # Create index.ts if not yet created
      [ -f "$dir/index.ts" ] || echo "// autogenerated" > "$dir/index.ts"
      relativeSubfolder=${subdir#"$dir/"}
      echo "export * from './$relativeSubfolder';" >> "$dir/index.ts"
      exportAdded=true
    fi
  done

  # If no exports were added, remove the index.ts file
  if [ "$exportAdded" = false ]; then
    [ -f "$dir/index.ts" ] && rm "$dir/index.ts"
  fi

  # Exports for ./src directory
  if [ "$dir" != "./src" ] && [ -f "$dir/index.ts" ]; then
    relativeDir="${dir#./src/}"
    echo "export * from './$relativeDir';" >> ./src/index.ts
  fi
done

# shoutout to Jetbrains AI Assistant
# took you a while, but you got there in the end